server:
  port: 8020
spring:
  datasource:
    data-username: sa
    password: null
    url: jdbc:h2:~/data/oauth2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        trace: true